PocketSphinx: src/libpocketsphinx/tmat.h File Reference
tmat.h File Reference
Transition matrix data structure.
#include <stdio.h>
#include <sphinxbase/logmath.h>
Data Structures
struct tmat_t
Transition matrix data structure.
Functions
tmat_t * tmat_init (char const *tmatfile, logmath_t *lmath, float64 tpfloor, int32 breport)
Initialize transition matrix.
void tmat_dump (tmat_t *tmat, FILE *fp)
Dumping the transition matrix for debugging.
void tmat_free (tmat_t *t)
RAH, add code to remove memory allocated by tmat_init.
void tmat_report (tmat_t *t)
Report the detail of the transition matrix structure.
Detailed Description
Transition matrix data structure.
Definition in file tmat.h.
Function Documentation
void tmat_dump (tmat_t * tmat, FILE * fp)
Dumping the transition matrix for debugging.
Parameters
tmat In: transition matrix
fp In: file pointer
Definition at line 129 of file tmat.c.
References tmat_t::n_state, tmat_t::n_tmat, and tmat_t::tp.
void tmat_free (tmat_t * t)
RAH, add code to remove memory allocated by tmat_init.
Parameters
t In: transition matrix
Definition at line 332 of file tmat.c.
References ckd_free(), ckd_free_3d(), and tmat_t::tp.
Referenced by acmod_free().
tmat_t* tmat_init (char const * tmatfile, logmath_t * lmath, float64 tpfloor, int32 breport)
Initialize transition matrix.
Parameters
tmatfile In: input file
lmath In: log math parameters
tpfloor In: floor value for each non-zero transition probability
breport In: whether reporting the process of tmat_t
Definition at line 191 of file tmat.c.
References bio_fread(), bio_hdrarg_free(), bio_readhdr(), bio_verify_chksum(), ckd_calloc, ckd_calloc_2d, ckd_calloc_3d, ckd_free_2d(), E_ERROR, E_FATAL, E_FATAL_SYSTEM, E_INFO, E_WARN, logmath_log(), tmat_t::n_state, tmat_t::n_tmat, SENSCR_SHIFT, and tmat_t::tp.
void tmat_report (tmat_t * t)
Report the detail of the transition matrix structure.
Parameters
t In: transition matrix
Definition at line 319 of file tmat.c.
References E_INFO_NOFN, tmat_t::n_state, and tmat_t::n_tmat.